# Generated by Django 5.2.1 on 2025-12-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinsumo',
            name='referencia',
            field=models.CharField(blank=True, help_text='Referencia externa (ej: Producción #123, Compra #456)', max_length=200, null=True),
        ),
    ]
