# Generated by Django 5.2.1 on 2025-05-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('mesero', 'Mesero'), ('cocinero', 'Cocinero'), ('gerente', 'Gerente'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
