# Generated by Django 5.2.1 on 2025-10-01 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name', 'username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está desactivado, no puede iniciar sesión'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='areas_permitidas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de áreas a las que tiene acceso el usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_ultimo_qr',
            field=models.DateTimeField(blank=True, help_text='Última vez que se generó un QR para este usuario', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN numérico de 4-6 dígitos para acceso rápido', max_length=6, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^\\d+$', 'El PIN debe contener solo números.')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='qr_token',
            field=models.UUIDField(blank=True, editable=False, help_text='Token único para autenticación vía QR', null=True, unique=True),
        ),
    ]
