# Generated by Django 5.2.1 on 2025-10-02 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_options_usuario_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN numérico de 4-6 dígitos - SOLO para cajeros', max_length=6, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^\\d+$', 'El PIN debe contener solo números.')]),
        ),
    ]
