# Generated by Django 5.2.1 on 2025-10-16 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que desactivó esta cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se desactivó el usuario (soft delete)', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está desactivado, no puede iniciar sesión (soft delete)'),
        ),
    ]
