# Generated by Django 5.2.1 on 2025-10-24 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_add_soft_delete_to_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para autenticación vía QR', unique=True)),
                ('ip_generacion', models.GenericIPAddressField(blank=True, help_text='IP del servidor cuando se generó el QR', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, el token puede usarse para login')),
                ('usado', models.BooleanField(default=False, help_text='Si ya se usó para hacer login')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del token')),
                ('fecha_uso', models.DateTimeField(blank=True, help_text='Fecha y hora en que se usó el token', null=True)),
                ('fecha_invalidacion', models.DateTimeField(blank=True, help_text='Fecha y hora en que se invalidó el token', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario al que pertenece este token', on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token QR',
                'verbose_name_plural': 'Tokens QR',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
