# Generated by Django 5.2.1 on 2025-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_qrtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de expiración del token (24h por defecto)', null=True),
        ),
        migrations.AddIndex(
            model_name='qrtoken',
            index=models.Index(fields=['token', 'activo', 'usado'], name='usuarios_qr_token_d93f94_idx'),
        ),
        migrations.AddIndex(
            model_name='qrtoken',
            index=models.Index(fields=['usuario', 'activo'], name='usuarios_qr_usuario_999574_idx'),
        ),
    ]
