# Generated by Django 5.1.4 on 2026-01-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_agregar_expiracion_qrtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('mesero', 'Mesero'), ('cocinero', 'Cocinero'), ('cajero', 'Cajero'), ('gerente', 'Gerente'), ('admin', 'Administrador')], default='cliente', help_text='Rol que determina los permisos del usuario', max_length=20),
        ),
    ]
