# Generated by Django 5.2.1 on 2025-12-24 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_agregar_expiracion_qrtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pin_secundario',
            field=models.CharField(blank=True, help_text='PIN secundario de 4-6 dígitos para operaciones sensibles', max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^\\d+$', 'El PIN secundario debe contener solo números.')]),
        ),
    ]
