# Generated by Django 5.2.1 on 2025-12-24 21:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_movimientoinsumo_referencia'),
        ('productos', '0006_producto_es_fabricable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1, help_text='Versión de la receta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_creadas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.OneToOneField(help_text='Producto que se fabrica con esta receta', on_delete=django.db.models.deletion.PROTECT, related_name='receta', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.DecimalField(decimal_places=3, help_text='Cantidad de producto fabricado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('lote', models.CharField(blank=True, help_text='Código de lote opcional', max_length=100, null=True)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('aplicada', 'Aplicada'), ('anulada', 'Anulada')], default='registrada', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('pin_secundario_validado', models.BooleanField(default=False, help_text='Marca si se validó PIN secundario para anular (NO guarda el PIN)')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones_anuladas', to=settings.AUTH_USER_MODEL)),
                ('aplicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='productos.producto')),
                ('receta', models.ForeignKey(help_text='Receta utilizada en esta producción', on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='produccion.receta')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad de insumo por 1 unidad de producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('merma_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de merma (ej: 5.00 = 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_que_lo_usan', to='inventario.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='produccion.receta')),
            ],
            options={
                'verbose_name': 'Ítem de Receta',
                'verbose_name_plural': 'Ítems de Receta',
                'ordering': ['insumo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_calculada', models.DecimalField(decimal_places=3, help_text='Cantidad consumida (receta * cantidad_producida + merma)', max_digits=10)),
                ('unidad_snapshot', models.CharField(help_text='Unidad del insumo al momento de la producción', max_length=20)),
                ('stock_insumo_antes', models.DecimalField(decimal_places=3, help_text='Stock del insumo antes de aplicar', max_digits=10)),
                ('stock_insumo_despues', models.DecimalField(decimal_places=3, help_text='Stock del insumo después de aplicar', max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones_detalle', to='inventario.insumo')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.produccion')),
            ],
            options={
                'verbose_name': 'Detalle de Producción',
                'verbose_name_plural': 'Detalles de Producción',
                'ordering': ['insumo__nombre'],
                'unique_together': {('produccion', 'insumo')},
            },
        ),
        migrations.AddIndex(
            model_name='produccion',
            index=models.Index(fields=['-fecha_creacion'], name='produccion__fecha_c_1da92d_idx'),
        ),
        migrations.AddIndex(
            model_name='produccion',
            index=models.Index(fields=['producto', 'estado'], name='produccion__product_74f53f_idx'),
        ),
        migrations.AddIndex(
            model_name='produccion',
            index=models.Index(fields=['lote'], name='produccion__lote_4bcbcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recetaitem',
            unique_together={('receta', 'insumo')},
        ),
    ]
