# Generated by Django 5.2.1 on 2025-06-22 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diario', 'Reporte Diario'), ('semanal', 'Reporte Semanal'), ('mensual', 'Reporte Mensual'), ('personalizado', 'Periodo Personalizado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pedidos', models.IntegerField(default=0)),
                ('promedio_por_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producto_mas_vendido', models.CharField(blank=True, max_length=200)),
                ('dia_mas_ventas', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/excel/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/pdf/')),
            ],
            options={
                'verbose_name': 'Reporte de Ventas',
                'verbose_name_plural': 'Reportes de Ventas',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='AnalisisProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('cantidad_vendida', models.IntegerField(default=0)),
                ('ingresos_generados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promedio_diario', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ranking_ventas', models.IntegerField(default=0)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Análisis de Producto',
                'verbose_name_plural': 'Análisis de Productos',
                'unique_together': {('producto', 'periodo_inicio', 'periodo_fin')},
            },
        ),
    ]
