# Generated by Django 5.2.1 on 2025-09-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reporteventas',
            unique_together={('tipo', 'fecha_inicio', 'fecha_fin')},
        ),
    ]
