# Generated by Django 5.2.1 on 2025-10-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_categoria'),
        ('reportes', '0002_alter_reporteventas_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='productos.producto'),
        ),
    ]
