# Generated by Django 5.2.1 on 2025-09-30 13:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0003_alter_detallepedido_options_alter_pedido_options_and_more'),
        ('productos', '0002_producto_requiere_inventario_producto_stock_actual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('agotado', 'Agotado'), ('reposicion', 'Necesita Reposición')], max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='activa', max_length=20)),
                ('stock_actual', models.IntegerField(help_text='Stock al momento de crear la alerta')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_stock', to='productos.producto')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('agregar_producto', 'Agregar Producto'), ('eliminar_producto', 'Eliminar Producto'), ('modificar_cantidad', 'Modificar Cantidad'), ('aplicar_descuento', 'Aplicar Descuento'), ('agregar_propina', 'Agregar Propina'), ('reasignar_mesa', 'Reasignar Mesa'), ('cancelar_pedido', 'Cancelar Pedido'), ('otro', 'Otro')], max_length=30)),
                ('detalle_anterior', models.JSONField(help_text='Estado antes del cambio')),
                ('detalle_nuevo', models.JSONField(help_text='Estado después del cambio')),
                ('motivo', models.TextField(blank=True, help_text='Razón del cambio', null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_modificaciones', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Modificación',
                'verbose_name_plural': 'Historial de Modificaciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('qr', 'Código QR'), ('movil', 'Pago Móvil')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='procesado', max_length=20)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('comprobante_externo', models.ImageField(blank=True, help_text='Captura o foto del comprobante', null=True, upload_to='comprobantes/')),
                ('referencia', models.CharField(blank=True, help_text='Referencia de pago digital', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('qr', 'Código QR'), ('movil', 'Pago Móvil')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('referencia', models.CharField(blank=True, help_text='Número de transacción, voucher, etc.', max_length=100, null=True)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='caja.transaccion')),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('turno', models.CharField(choices=[('manana', 'Mañana (06:00 - 14:00)'), ('tarde', 'Tarde (14:00 - 22:00)'), ('noche', 'Noche (22:00 - 06:00)'), ('completo', 'Día Completo')], max_length=20)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('efectivo_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo al abrir caja', max_digits=10)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_qr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_movil', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, help_text='Suma de todos los métodos', max_digits=10)),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, default=0, help_text='Inicial + ventas efectivo', max_digits=10)),
                ('efectivo_real', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo contado físicamente', max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Real - Esperado', max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_propinas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_pedidos', models.IntegerField(default=0, help_text='Total de pedidos en el turno')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('hora_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha', '-hora_apertura'],
                'unique_together': {('cajero', 'fecha', 'turno')},
            },
        ),
    ]
