# Generated by Django 5.2.1 on 2025-10-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_jornadalaboral'),
        ('productos', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertastock',
            name='producto_nombre',
            field=models.CharField(default='Producto sin nombre', help_text='Nombre del producto (guardado para historial)', max_length=100),
        ),
        migrations.AlterField(
            model_name='alertastock',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_stock', to='productos.producto'),
        ),
    ]
