# Generated by Django 5.2.1 on 2025-12-23 14:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alertastock_producto_nombre_and_more'),
        ('mesas', '0004_add_soft_delete_to_mesa'),
        ('pedidos', '0007_add_unique_constraint_pedido_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='pedidos.pedido'),
        ),
        migrations.CreateModel(
            name='CuentaMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('con_deuda', 'Cerrada con Deuda'), ('cancelada', 'Cancelada')], default='abierta', help_text='Estado de la cuenta', max_length=20)),
                ('total_acumulado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de todos los pedidos de esta cuenta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total pagado hasta el momento', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de apertura de la cuenta')),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha y hora de cierre de la cuenta', null=True)),
                ('deuda_autorizada', models.BooleanField(default=False, help_text='Si True, se cerró con deuda mediante PIN secundario')),
                ('motivo_deuda', models.TextField(blank=True, help_text='Motivo por el que se autorizó cerrar con deuda', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales de la cuenta', null=True)),
                ('abierta_por', models.ForeignKey(help_text='Usuario que abrió la cuenta (mesero/cliente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('autorizada_por', models.ForeignKey(blank=True, help_text='Usuario que autorizó el cierre con deuda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deudas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('cerrada_por', models.ForeignKey(blank=True, help_text='Usuario que cerró la cuenta (cajero)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_cerradas', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(help_text='Mesa asociada a esta cuenta', on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='mesas.mesa')),
            ],
            options={
                'verbose_name': 'Cuenta de Mesa',
                'verbose_name_plural': 'Cuentas de Mesa',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cuenta',
            field=models.ForeignKey(blank=True, help_text='Cuenta de mesa a la que se aplica este pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='caja.cuentamesa'),
        ),
        migrations.AddIndex(
            model_name='cuentamesa',
            index=models.Index(fields=['mesa', 'estado'], name='caja_cuenta_mesa_id_61ae71_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentamesa',
            index=models.Index(fields=['fecha_apertura'], name='caja_cuenta_fecha_a_044217_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentamesa',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('mesa',), name='unique_cuenta_abierta_por_mesa', violation_error_message='Ya existe una cuenta abierta para esta mesa'),
        ),
    ]
