# Generated by Django 5.1.4 on 2026-01-06 05:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_backfill_cuentas_mesa'),
        ('pedidos', '0011_pedido_reembolso_estado_pedido_total_pagado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('qr', 'Código QR'), ('tarjeta', 'Tarjeta'), ('movil', 'Pago Móvil')], max_length=20)),
                ('motivo', models.TextField(help_text='Razón del reembolso')),
                ('codigo_autorizacion', models.CharField(blank=True, help_text='Código PIN o token de autorización', max_length=64, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos_creados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
