# Generated by Django 5.1.4 on 2026-01-09 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_reembolso'),
        ('pedidos', '0012_remove_pedido_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='reembolso',
            name='autorizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Autorización'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', help_text='Estado del reembolso', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='pedidos.pedido'),
        ),
        migrations.DeleteModel(
            name='CuentaMesa',
        ),
    ]
