# Generated by Django 5.2.1 on 2025-09-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='requiere_inventario',
            field=models.BooleanField(default=False, help_text='Si requiere control de stock'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0, help_text='Cantidad disponible en inventario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, help_text='Stock mínimo antes de alerta'),
        ),
    ]
