# Generated by Django 5.2.1 on 2025-10-16 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si False, la categoría está eliminada (soft delete)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_eliminadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se eliminó la categoría', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si False, el producto está eliminado (soft delete)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se eliminó el producto', null=True),
        ),
    ]
