# Generated by Django 5.2.1 on 2025-12-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_fabricable',
            field=models.BooleanField(default=False, help_text='Indica si el producto se fabrica mediante producción (requiere receta)'),
        ),
    ]
