# Generated by Django 5.2.1 on 2025-11-29 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Restaurante QR', help_text='Nombre del restaurante', max_length=200)),
                ('nit', models.CharField(blank=True, help_text='NIT del negocio', max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del local', null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email de contacto', max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo del restaurante', null=True, upload_to='configuracion/logos/')),
                ('lema', models.CharField(blank=True, help_text='Lema o eslogan del restaurante', max_length=300, null=True)),
                ('moneda', models.CharField(default='Bs/', help_text='Símbolo de moneda', max_length=10)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.0, help_text='Impuesto en porcentaje (ej: 13.00 para 13%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('propina_sugerida', models.DecimalField(decimal_places=2, default=10.0, help_text='Propina sugerida en porcentaje', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text='Idioma del sistema', max_length=10)),
                ('zona_horaria', models.CharField(default='America/La_Paz', help_text='Zona horaria del sistema', max_length=50)),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro')], default='oscuro', help_text='Tema visual del sistema', max_length=20)),
                ('hora_apertura', models.TimeField(default='08:00:00', help_text='Hora de apertura del restaurante')),
                ('hora_cierre', models.TimeField(default='22:00:00', help_text='Hora de cierre del restaurante')),
                ('reserva_max_minutos', models.IntegerField(default=120, help_text='Duración máxima de una reserva en minutos', validators=[django.core.validators.MinValueValidator(30)])),
                ('reserva_tolerancia_minutos', models.IntegerField(default=15, help_text='Tolerancia en minutos antes de marcar no-show', validators=[django.core.validators.MinValueValidator(5)])),
                ('ticket_footer', models.TextField(blank=True, help_text='Texto al pie del ticket (mensaje de agradecimiento, redes sociales, etc.)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
