# Generated by Django 5.2.1 on 2025-06-21 22:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carnet', models.CharField(max_length=20, verbose_name='Número de Carnet/CI')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de Reserva')),
                ('hora_reserva', models.TimeField(verbose_name='Hora de Reserva')),
                ('numero_personas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Personas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_uso', 'En Uso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No Show')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.mesa', verbose_name='Mesa Asignada')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva', '-hora_reserva'],
            },
        ),
    ]
