# Generated by Django 5.2.1 on 2025-10-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_mesa_capacidad_mesa_disponible_mesa_posicion_x_and_more'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='mesas.mesa', verbose_name='Mesa Asignada'),
        ),
    ]
