# Generated by Django 5.2.1 on 2025-09-30 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_forma_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='cajero_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cobrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de descuento', max_digits=5),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado Completo'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del pago', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='modificado',
            field=models.BooleanField(default=False, help_text='Indica si el pedido fue modificado por caja'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto ya pagado', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas del pedido', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones_caja',
            field=models.TextField(blank=True, help_text='Notas del cajero', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='propina',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Propina adicional', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='reasignado',
            field=models.BooleanField(default=False, help_text='Indica si fue reasignado a otra mesa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_final',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total con descuento y propina', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en preparacion', 'En Preparación'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('qr', 'Código QR'), ('movil', 'Pago Móvil'), ('mixto', 'Pago Mixto')], default='efectivo', max_length=20, null=True),
        ),
    ]
