# Generated by Django 5.2.1 on 2025-10-02 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_mesa_capacidad_mesa_disponible_mesa_posicion_x_and_more'),
        ('pedidos', '0003_alter_detallepedido_options_alter_pedido_options_and_more'),
        ('productos', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedidos', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='mesas.mesa'),
        ),
    ]
