# Generated by Django 5.2.1 on 2025-10-15 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_detallepedido_producto_alter_pedido_mesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesero_comanda',
            field=models.ForeignKey(blank=True, help_text='Mesero que tomó el pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_comandados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_personas',
            field=models.PositiveIntegerField(default=1, help_text='Número de personas en la mesa'),
        ),
    ]
