# Generated by Django 5.2.1 on 2025-10-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_mesero_comanda_pedido_numero_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='cantidad_pagada',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de este producto ya pagada'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio del producto al momento del pedido', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en preparacion', 'En Preparación'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('solicitando_cuenta', 'Cliente Solicitó Cuenta')], default='pendiente', max_length=20),
        ),
    ]
