# Generated by Django 5.2.1 on 2025-12-23 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0004_add_soft_delete_to_mesa'),
        ('pedidos', '0006_add_precio_unitario_and_cantidad_pagada_to_detalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'en preparacion', 'listo'])), fields=('mesa',), name='unique_pedido_activo_por_mesa', violation_error_message='Ya existe un pedido activo para esta mesa'),
        ),
    ]
