# Generated by Django 5.2.1 on 2025-12-23 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_add_cuenta_mesa_model'),
        ('pedidos', '0007_add_unique_constraint_pedido_activo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='unique_pedido_activo_por_mesa',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cuenta',
            field=models.ForeignKey(blank=True, help_text='Cuenta de mesa a la que pertenece este pedido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='caja.cuentamesa'),
        ),
    ]
