# Generated by Django 5.1.4 on 2026-01-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_add_cuenta_mesa_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('creado', 'Creado'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En Preparación'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('cerrado', 'Cerrado')], default='creado', max_length=20),
        ),
    ]
