# Generated by Django 5.1.4 on 2026-01-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_stock',
            field=models.BooleanField(default=False, help_text='Indica si ya se descontó stock para este pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Motivo de cancelación del pedido', null=True),
        ),
    ]
