# Generated by Django 5.1.4 on 2026-01-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedido_descuento_stock_pedido_motivo_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='reembolso_estado',
            field=models.CharField(choices=[('none', 'Sin reembolso'), ('parcial', 'Reembolso parcial'), ('total', 'Reembolso total')], default='none', help_text='Estado del reembolso', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total pagado acumulado (todas las transacciones)', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_reembolsado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total reembolsado acumulado', max_digits=10),
        ),
    ]
