# Generated by Django 5.1.4 on 2026-01-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_reembolso_estado_pedido_total_pagado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cuenta',
        ),
    ]
