# Generated by Django 5.2.1 on 2025-09-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='capacidad',
            field=models.PositiveIntegerField(default=4, help_text='Número de personas que caben en la mesa'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Mesa activa para uso'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='posicion_x',
            field=models.IntegerField(default=0, help_text='Posición X en el mapa'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='posicion_y',
            field=models.IntegerField(default=0, help_text='Posición Y en el mapa'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('pagando', 'Pagando')], default='disponible', max_length=20),
        ),
    ]
