# Generated by Django 5.2.1 on 2025-10-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_mesa_capacidad_mesa_disponible_mesa_posicion_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='capacidad_combinada',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad total cuando está combinada'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='es_combinada',
            field=models.BooleanField(default=False, help_text='Indica si está unida con otra mesa'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='mesas_combinadas',
            field=models.CharField(blank=True, help_text='IDs de mesas combinadas (ej: "1,2,3")', max_length=100, null=True),
        ),
    ]
