# Generated by Django 5.2.1 on 2025-10-16 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_mesa_capacidad_combinada_mesa_es_combinada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si False, la mesa está eliminada (soft delete)'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_eliminadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mesa',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se eliminó la mesa', null=True),
        ),
    ]
